### PR TITLE
[full-ci] Simplify link creation in Files/Sidebar

### LINKED ISSUE #6962: "add link" should directly create a new link
### Steps to reproduce
1. open https://ocis.ocis-wopi.released.owncloud.works/s/rmTOvgNZzALYFzP
2. click on "copy quicklink" quickaction
3. click on "add link" in the sidebar
4. inline menu to create a new link opens

### Expected behaviour
- new link should be created
- new link should be added on top of the link-list (directly below the "add link" button)

https://user-images.githubusercontent.com/26610733/168156635-e1805e9c-5bc1-44c1-a148-65aae3bf368e.mp4

### Actual behaviour
Tell us what happens instead
- inline menu appears

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
This will most likely be a bit of a pain in the acceptance tests, but simplifies link creation by the user and reduces code complexity by quite a bit

It also shifts from using the capability-based defaultLinkName to a translatable default defined in the frontend

## Related Issue
- Fixes #6962

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/25552/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/25552/tracing/public-link-alice-2022-5-12-03-53-57.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/25552/tracing/unstructured-collection-of-testable-space-interactions-alice-2022-5-12-03-55-28.zip 


</p></details>

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 1]
```diff
@@ -375,12 +339,66 @@ export default defineComponent({
       return l1Direct ? -1 : 1
     },
 
+    checkPasswordEnforcedFor(link) {
+      const currentRole = this.availableRoleOptions.find(({ role }) => {
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:343]: There is `LinkShareRoles.getByBitmask` which feels more appropriate than bitmask comparisons. But I guess filtering the `availableRoleOptions` was on purpose? Do you see a way to incorporate the `getByBitmask` method anyway?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 2]
```diff
@@ -375,12 +339,66 @@ export default defineComponent({
...
+        return parseInt(link.permissions) === role.bitmask(false)
+      })
+
+      const canRead = currentRole.role.hasPermission(SharePermissions.read)
+      const canCreate = currentRole.role.hasPermission(SharePermissions.create)
+      const canDelete = currentRole.role.hasPermission(SharePermissions.delete)
+
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:350]: What about the `update` permission for all the checks below?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 3]
```diff
@@ -375,12 +339,66 @@ export default defineComponent({
...
+        })
+      } else {
+        this.createLink({ params: paramsToCreate, onError })
+      }
+    },
+
+    checkLinkToUpdate({ link, onSuccess = () => {} }) {
+      const params = this.getParamsForLink(link)
+
+      if (this.checkPasswordEnforcedFor(link)) {
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:394]: huh? this will enforce to set a new password on any edit action of a link, no?

**Review by kulmann — CHANGES_REQUESTED** [review]
Some weird findings (please check if you can reproduce those before digging into code):
- using `ENTER` in password prompt continues with link creation but doesn't close the modal
- setting password enforcement for read only public links and trying to set a different role on an existing link doesn't work. I get the confirmation toast but the role is not updated.

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 3 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:394]: Shouldn't, let me double-check. But the idea was to check if passwords are enforced and if yes show the modal (and then progress in the update progress upon password submit) and if no then directly progress with the update

Upon second look we need to check _if the already has a password_, too. Not sure if you were hinting at that?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 2 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:350]: Good point, I went by the roles (instead of permissions) and since enforcement is an oc10-only capability as of now and there is no "Updater" role I'm aware of this was forgotten. Adding it now

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 3 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue]: True yeah, I've added a mitigation. Thanks!

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 1 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue]: No clue where&why the mapping in the line below ever was introduced in the past (we found, disliked but accepted&reused the code previously found). I went for your suggested solution and seems to work like a charm

**Comment by pascalwengerter** [comment]
`webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:278` fails in CI, can't reproduce locally. Can someone else take a look?

**Comment by pascalwengerter** [comment]
@individual-it could your team take a look?
`webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:278` fails reliably in CI (e.g. https://drone.owncloud.com/owncloud/web/25984/38/20, but that was a re-run already), but passes reliably when I run the tests locally. Seems to be a hickup in the middleware

**Comment by individual-it** [comment]
@pascalwengerter will do, but most likely we will not be able to do it this week

**Comment by pascalwengerter** [comment]
Just rebased, only one CI failure which passes reliable locally - restarted CI to see if it's (potentially) flaky

https://drone.owncloud.com/owncloud/web/26061/38/20

**Comment by grgprarup** [comment]
> Just rebased, only one CI failure which passes reliable locally - restarted CI to see if it's (potentially) flaky
> 
> https://drone.owncloud.com/owncloud/web/26061/38/20

@pascalwengerter I am looking into it. I run it on my local machine, sometimes it gets passed, and sometimes fails. But after using a delay before fetching the Share details it always passes. Needs more investigation.

**Comment by grgprarup** [comment]
@pascalwengerter are you aware of this message `Failed to create link` and `Link was created successfully` when adding a link. And sidebar is not updated. Need to `close` and `reopen` sidebar to see link.
failed

**Comment by pascalwengerter** [comment]
> @pascalwengerter are you aware of this message `Failed to create link` and `Link was created successfully` when adding a link. And sidebar is not updated. Need to `close` and `reopen` sidebar to see link. failed

Didn't see this, which backend/setup are you using (e.g. required passwords/expiration dates) and which button did you press (assuming `Add link` in the sidebar)?

**Comment by grgprarup** [comment]
> > @pascalwengerter are you aware of this message `Failed to create link` and `Link was created successfully` when adding a link. And sidebar is not updated. Need to `close` and `reopen` sidebar to see link. failed
> 
> Didn't see this, which backend/setup are you using (e.g. required passwords/expiration dates) and which button did you press (assuming `Add link` in the sidebar)?

backend: oc10
When `Add link` was clicked, when `Enforce password protection for read-only links` was not enabled.
When the password `set` button was clicked, when `Enforce password protection for read-only links` was enabled.
Tried with `simplify-sidebar-link-creation` branch
input_password

**Comment by pascalwengerter** [comment]
> backend: oc10 When `Add link` was clicked, when `Enforce password protection for read-only links` was not enabled. When the password `set` button was clicked, when `Enforce password protection for read-only links` was enabled. Tried with `simplify-sidebar-link-creation` branch 

I don't fully get what you're writing. If you first log in as user and then change the enforcement in the settings, we run into the problem of caches capabilities so this is nothing that needs further investigation (since it's known/broken by design).

My problem is that `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:27{6,8}` fails reliably in CI and passes reliably for me when running the dockerized acceptance tests

File: tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md [hunk 4]
```diff
@@ -170,16 +170,11 @@ Other free text and markdown formatting can be used elsewhere in the document if
...
--   [webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:284](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature#L284)
--   [webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:293](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature#L293)
--   [webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:302](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature#L302)
--   [webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:311](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature#L311)
+-   [webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:278](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature#L278)
```
Comment (individual-it) [inline tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md:177]: I think this line is still 276
image

Comment (pascalwengerter) [reply tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md:177]: Yeah, about to push a fix

Comment (pascalwengerter) [reply tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md:177]: Found some more stuff, linting and committing now

**Comment by individual-it** [comment]
`yarn install` keeps on failing :-(

File: tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js [hunk 5]
```diff
@@ -488,7 +488,10 @@ module.exports = {
         .setValue('@dialogInput', password)
         .useCss()
 
-      await this.click('@dialogConfirmBtnEnabled')
+      await this.waitForElementVisible('@dialogConfirmBtnEnabled')
+        .initAjaxCounters()
+        .click('@dialogConfirmBtnEnabled')
+        .waitForOutstandingAjaxCalls()
```
Comment (grgprarup) [inline tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js:494]: @pascalwengerter I have made these changes. IMO this might fix the `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:27{6,8}` failure.
