### PR TITLE
Fix: always, show location in top bar, make file picker work in various locations, file picker width too narrow

### LINKED ISSUE #11895: "Open" / "Save as" feature does not work for incoming shares
## Describe the bug
The "Open" / "Save as" feature in editors does not work for incoming shares. It's broken for both single file shares as well as for files inside shared folders.

## Steps to reproduce
1. Share a text file with admin
2. As admin, open this text file with the text editor
3. Open the context menu on the top and click "Open"

## Expected behavior
The file picker opens with the current location.

## Actual behavior
It shows an error because the PROPFIND fails.

### LINKED ISSUE #11896: Location is missing in app top bar for incoming shares
## Describe the bug
The Location is missing in app top bar for incoming shares. This is broken for both single file shares as well as for files inside shared folders.

## Steps to reproduce
1. Share a text file with admin
2. As admin, open this text file with the text editor

## Expected behavior
The location is present in the app top bar.

## Actual behavior
The location is missing in the app top bar.

image

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #11895 
- Fixes #11896 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by AlexAndBear** [comment]
Opened an additional issue in OCIS repo https://github.com/owncloud/ocis/issues/10562 so we can remove the workaround later

File: changelog/unreleased/bugfix-app-top-bar-does-not-show-location-when-shared-file-is-opened [hunk 1]
```diff
@@ -0,0 +1,6 @@
+Bugfix: App top bar does not show location when shared file is opened
+
+We've fixed an issue where the app top bar did not show the location when a shared file was opened.
+
+https://github.com/owncloud/web/pull/11900
+https://github.com/owncloud/web/issues/11895
```
Comment (JammingBen) [inline changelog/unreleased/bugfix-app-top-bar-does-not-show-location-when-shared-file-is-opened:6]:
```suggestion
https://github.com/owncloud/web/issues/11896
```

File: packages/web-pkg/src/components/AppTopBar.vue [hunk 2]
```diff
@@ -158,38 +156,13 @@ export default defineComponent({
...
     })
 
-    const { getParentFolderName, getParentFolderLinkIconAdditionalAttributes, getPathPrefix } =
-      useFolderLink()
-
-    const space = computed(() => getMatchingSpace(props.resource))
-
-    //FIXME: We currently have problems to display the parent folder name of a shared file, so we disabled it for now
-    const isPathDisplayed = computed(() => {
-      return !isShareSpaceResource(unref(space)) && !isPublicSpaceResource(unref(space))
```
Comment (JammingBen) [inline packages/web-pkg/src/components/AppTopBar.vue:168]: The public space condition is still needed, otherwise the Location shows "Personal" on public pages.

File: packages/web-pkg/src/composables/folderLink/useFolderLink.ts [hunk 3]
```diff
@@ -67,7 +67,10 @@ export const useFolderLink = (options: ResourceRouteResolverOptions = {}) => {
       space,
       path: dirname(resource.path)
     })
-    if (isShareRoot(resource) || !parentFolderAccessible) {
+
+    //FIXME: As soon the backend exposes oc-share-root via webdav, only use isShareRoot fn
+    const shareRoot = isShareRoot(resource) || resource.id === space.id
```
Comment (JammingBen) [inline packages/web-pkg/src/composables/folderLink/useFolderLink.ts:72]: Arghs, `resource.id === space.id` is an issue for spaces. When you e.g. search for a space, then the space's parent is now "Shared with me". I guess we need this: `isShareRoot(resource) || (resource.id === space.id && resource.type === 'file')`

**Review by JammingBen — COMMENTED** [review]
I found 2 little bugs while testing.

File: packages/web-pkg/src/composables/folderLink/useFolderLink.ts (hunk 3 above)
Comment (AlexAndBear) [reply packages/web-pkg/src/composables/folderLink/useFolderLink.ts:72]: @butonic is coming up with a fix, I think we can leave this open until we got it and remove the "gehampel 🤡 " along

Comment (JammingBen) [reply packages/web-pkg/src/composables/folderLink/useFolderLink.ts:72]: Ahh nice 👍

Comment (AlexAndBear) [reply packages/web-pkg/src/composables/folderLink/useFolderLink.ts]: Unfortantly the fix won't come, but I enhanced the condition
