### PR TITLE
[tests-only][full-ci] Wait for upload success message

### LINKED ISSUE #7143: `webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature` failed nightly
Build: https://drone.owncloud.com/owncloud/web/26303/67/15

`webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:159`

```
@mailhog @public_link_share-feature-required
  Scenario: creating a public link with "Editor" role makes it possible to upload a folder # features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:159
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (228ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created folder "simple-folder" in the server
    Given user "Alice" has shared folder "simple-folder" with link with "read, update, create, delete" permissions in the server
    When the public uses the webUI to access the last public link created by user "Alice" in a new session
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (278ms).
  Using: chrome (94.0.4606.61) on Linux platform.

√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 579 milliseconds.
    And the user uploads folder "PARENT" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 25 milliseconds.
√ Element <#files-file-upload-button> was visible after 23 milliseconds.
√ Element <#upload-info> was visible after 27 milliseconds.
√ Element <#upload-info #close-upload-info-btn> was visible after 27 milliseconds.
 Error while running .clickElement() protocol action: The command failed because the referenced element is no longer attached to the DOM. – stale element reference: element i...

   TimeoutError: An error occurred while running .click() command on <Element [name=@filesFoldersUploadProgressClose]>: 
   {"status":-1,"message":"Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null","stack":"TypeError: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null\n    at Selenium2Protocol.getElementId (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/transport/selenium2.js:9:20)\n    at ClickElement.elementFound (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/element/command.js:165:39)\n    at action (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/api/element-commands/_baseElementCommand.js:55:36)\n    at PeriodicPromise.perform (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:86:31)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at PeriodicPromise.runAction (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:48:22)\n    at PeriodicPromise.runAction (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:51:16)"}
       at Page.closeFileFolderUploadProgress (/var/www/owncloud/web/tests/acceptance/pageObjects/personalPage.js:174:77)
       at Proxy.uploadFolder (/var/www/owncloud/web/tests/acceptance/pageObjects/personalPage.js:225:10)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:253:37)
    Then folder "PARENT" should be listed on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='PARENT' or @data-test-resource-path='/PARENT') and @data-test-resource-type='folder']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 28 milliseconds.
    And folder "CHILD" should be listed in the folder "PARENT" on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='PARENT' or @data-test-resource-path='/PARENT')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 23 milliseconds.
 Error while running .clickElement() protocol action: An unknown error has occurred – element click intercepted: Element <a href="/files/public/show/UjsfDEPbLQDmbev/PARENT" c...

   TimeoutError: An error occurred while running .click() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='PARENT' or @data-test-resource-path='/PARENT') and @data-test-resource-type='folder']/parent::*>:   (Session info: chrome=94.0.4606.61),  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.4.0-110-generic x86_64); element click intercepted: Element <a href="/files/public/show/UjsfDEPbLQDmbev/PARENT" class="oc-text-overflow">...</a> is not clickable at point (138, 251). Other element would receive the click: <div class="tippy-content" data-state="visible" style="transition-duration: 300ms;">...</div>
   {"status":-1,"state":"","code":"","value":{"message":"element click intercepted: Element <a href=\"/files/public/show/UjsfDEPbLQDmbev/PARENT\" class=\"oc-text-overflow\">...</a> is not clickable at point (138, 251). Other element would receive the click: <div class=\"tippy-content\" data-state=\"visible\" style=\"transition-duration: 300ms;\">...</div>","error":["  (Session info: chrome=94.0.4606.61)","  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.4.0-110-generic x86_64)"]},"errorStatus":64,"error":"An unknown error has occurred – element click intercepted: Element <a href=\"/files/public/show/UjsfDEPbLQDmbev/PARENT\" c...","httpStatusCode":200}
       at Proxy.navigateToFolder (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:215:29)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:958:5)
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 19 milliseconds.
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='CHILD' or @data-test-resource-path='/CHILD')]>: 
   {"sessionId":"977fada7f45d040d58dbb088f3adecaf","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:960:15)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='CHILD' or @data-test-resource-path='/CHILD')]>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:960:5)
    And file "child.txt" should be listed in the folder "CHILD" on the webUI
    - skipped
    And as "Alice" file "simple-folder/PARENT/CHILD/child.txt" should exist in the server
    - skipped
saving screenshot of failed test
```

Build: https://drone.owncloud.com/owncloud/web/26298/67/15

<details>
<summary>webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:169</summary>
  @mailhog @public_link_share-feature-required
  Scenario: creating a public link with "Editor" role makes it possible to upload a folder inside a subdirectory # features/webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:169
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (451ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created folder "simple-folder" in the server
    Given user "Alice" has created folder "simple-folder/simple-empty-folder" in the server
    And user "Alice" has shared folder "simple-folder" with link with "read, update, create, delete" permissions in the server
    When the public uses the webUI to access the last public link created by user "Alice" in a new session
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (371ms).
  Using: chrome (94.0.4606.61) on Linux platform.

√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 934 milliseconds.
    And the user opens folder "simple-empty-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-empty-folder' or @data-test-resource-path='/simple-empty-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 31 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 86 milliseconds.
    And the user uploads folder "PARENT" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 39 milliseconds.
√ Element <#files-file-upload-button> was visible after 50 milliseconds.
√ Element <#upload-info> was visible after 43 milliseconds.
√ Element <#upload-info #close-upload-info-btn> was visible after 41 milliseconds.
 Error while running .clickElement() protocol action: The command failed because the referenced element is no longer attached to the DOM. – stale element reference: element i...

   TimeoutError: An error occurred while running .click() command on <Element [name=@filesFoldersUploadProgressClose]>: 
   {"status":-1,"message":"Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null","stack":"TypeError: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null\n    at Selenium2Protocol.getElementId (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/transport/selenium2.js:9:20)\n    at ClickElement.elementFound (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/element/command.js:165:39)\n    at action (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/api/element-commands/_baseElementCommand.js:55:36)\n    at PeriodicPromise.perform (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:86:31)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at PeriodicPromise.runAction (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:48:22)\n    at PeriodicPromise.runAction (/var/www/owncloud/web/tests/acceptance/node_modules/nightwatch/lib/utils/periodic-promise.js:51:16)"}
       at Page.closeFileFolderUploadProgress (/var/www/owncloud/web/tests/acceptance/pageObjects/personalPage.js:174:77)
       at Proxy.uploadFolder (/var/www/owncloud/web/tests/acceptance/pageObjects/personalPage.js:225:10)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:253:37)
    Then folder "PARENT" should be listed on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='PARENT' or @data-test-resource-path='/PARENT') and @data-test-resource-type='folder']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 44 milliseconds.
    And folder "CHILD" should be listed in the folder "PARENT" on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='PARENT' or @data-test-resource-path='/PARENT')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 30 milliseconds.
 Error while running .clickElement() protocol action: An unknown error has occurred – element click intercepted: Element <a href="/files/public/show/BZYoOxjpaMnJzjQ/simple-em...

   TimeoutError: An error occurred while running .click() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='PARENT' or @data-test-resource-path='/PARENT') and @data-test-resource-type='folder']/parent::*>:   (Session info: chrome=94.0.4606.61),  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.4.0-110-generic x86_64); element click intercepted: Element <a href="/files/public/show/BZYoOxjpaMnJzjQ/simple-empty-folder/PARENT" class="oc-text-overflow">...</a> is not clickable at point (138, 251). Other element would receive the click: <div class="tippy-content" data-state="visible" style="transition-duration: 300ms;">...</div>
   {"status":-1,"state":"","code":"","value":{"message":"element click intercepted: Element <a href=\"/files/public/show/BZYoOxjpaMnJzjQ/simple-empty-folder/PARENT\" class=\"oc-text-overflow\">...</a> is not clickable at point (138, 251). Other element would receive the click: <div class=\"tippy-content\" data-state=\"visible\" style=\"transition-duration: 300ms;\">...</div>","error":["  (Session info: chrome=94.0.4606.61)","  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 5.4.0-110-generic x86_64)"]},"errorStatus":64,"error":"An unknown error has occurred – element click intercepted: Element <a href=\"/files/public/show/BZYoOxjpaMnJzjQ/simple-em...","httpStatusCode":200}
       at Proxy.navigateToFolder (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:215:29)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:958:5)
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 40 milliseconds.
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='CHILD' or @data-test-resource-path='/CHILD')]>: 
   {"sessionId":"ddcf552aff4e9f21b5bba1501af36889","status":0,"value":[]}
       at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:960:15)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='CHILD' or @data-test-resource-path='/CHILD')]>:
          at Proxy.checkFileName (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/var/www/owncloud/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at World.<anonymous> (/var/www/owncloud/web/tests/acceptance/stepDefinitions/filesContext.js:960:5)
    And file "child.txt" should be listed in the folder "CHILD" on the webUI
    - skipped
    And as "Alice" file "simple-folder/simple-empty-folder/PARENT/CHILD/child.txt" should exist in the server
    - skipped
saving screenshot of failed test
</details>

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
Sometimes `uploadFolder` might fail to close the upload-info dialog due to change in element reference (for what may be the reason). In this PR, I have made upload functions to wait for upload-status message to be visible and then only close the dialog.

## Related Issue
- Fixes #7143

## How Has This Been Tested?
- test environment: local

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/26312/73/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIUpload-uploadFileGreaterThanQuotaSize_feature-L12.png
  


</p></details>

File: tests/acceptance/pageObjects/personalPage.js [hunk 1]
```diff
@@ -418,6 +408,9 @@ module.exports = {
     fileUploadProgress: {
       selector: '#upload-info'
     },
+    fileUploadStatus: {
+      selector: '.upload-info-status .upload-info-success, .upload-info-status .upload-info-danger'
```
Comment (saw-jan) [inline tests/acceptance/pageObjects/personalPage.js:412]: Should I check for either success or fail selector and make the upload function pass on (_done above_) and let the **Then** step assert the result?
Or, make strict checks for success inside the upload function and create separate `tries to upload` step for tests like [this](https://drone.owncloud.com/owncloud/web/26312/51/20) (where upload should fail)?

Comment (saw-jan) [reply tests/acceptance/pageObjects/personalPage.js:412]: the `When` step should not concern with whether the upload succeeded or failed

**Review by individual-it — APPROVED** [review]

File: tests/acceptance/pageObjects/personalPage.js (hunk 1 above)
Comment (individual-it) [reply tests/acceptance/pageObjects/personalPage.js:412]: I think having a general selector is OK
