### PR TITLE
Split (in)direct link shares in sidebar into two lists

### LINKED ISSUE #7132: Sharing-Panel: Indirect links mess up the "Share via link"-Section
### Steps to reproduce
1. Login to https://ocis.ocis-web.latest.owncloud.works/
2. Create folderstructure: Personal: "Folder 1" / "Folder 2" / "Folder 3" 
3. Create multiple links for each Folder 1, Folder 2 and Folder 3
4. Look at the "Share via link" Section: Indirect links mess up the "Share via link"-Section.
image

### Expected behaviour
- clear visual focus on the direct links
- [ ] Add subsection "Indirect links (xx)"
- [ ] "Indirect links (xx)" shows number of indirect links
- [ ] "Indirect links (xx)" can be expanded/collapsed (default=collapsed)
- [ ] if there are no indirect links, the subsection "Indirect links" is not shown
- [ ] "show all ⌄" with a caret-down icon next to it to make it a little bit more prominent. 
- [ ] "Show all ⌄" is also used as wording for the direct-links-switch
- [ ] Add "Contextual Help"- Question mark. content: TBD @tbsbdr  

image

### Actual behaviour
Indirect links mess up the "Share via link"-Section.

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes #7132

### CODE REVIEW

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 1]
```diff
@@ -63,7 +63,40 @@
...
+          <oc-icon :name="collapseButtonIcon" fill-type="line" />
+        </oc-button>
+      </div>
+      <div v-if="indirectLinks.length">
+        <hr class="link-separator oc-my-m" />
+        <h3 class="oc-text-bold oc-m-rm oc-text-initial">
+          <span v-text="indirectLinksHeading" />
+          <oc-contextual-helper v-if="helpersEnabled" v-bind="indirectLinkHelp" />
+        </h3>
+        <oc-list v-if="displayIndirectLinks.length" class="oc-overflow-hidden oc-my-m">
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:77]: Why the new computed prop? Using `!indirectLinkListCollapsed` for the `v-if` here and then iterating over the `indirectLinks` for the `li`s does the same afaict.

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 2]
```diff
@@ -63,7 +63,40 @@
...
+            <details-and-edit
+              :available-role-options="availableRoleOptions"
+              :expiration-date="expirationDate"
+              :is-folder-share="highlightedFile.isFolder"
+              :is-modifiable="false"
+              :link="link"
+            />
+          </li>
+        </oc-list>
+        <div v-if="indirectLinks.length > 3" class="oc-flex oc-flex-center">
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:94]: Indirect link collapse/expand toggle is about `show 0` vs `show all`, no? I think you can get rid of the `v-if="indirectLinks.length > 3"` check entirely.

File: packages/web-app-files/src/helpers/contextualHelpers.js [hunk 3]
```diff
@@ -46,6 +46,9 @@ export const shareViaLinkHelp = {
     )
   ]
 }
+export const shareViaIndirectLinkHelp = {
+  text: $gettext('This file is shared, because one of the folders it is in is shared via link.')
```
Comment (kulmann) [inline packages/web-app-files/src/helpers/contextualHelpers.js:50]: What about something like `This file is shared, because one of the parent folders is shared via link.`? Is parent folder too technical?

Comment (pascalwengerter) [reply packages/web-app-files/src/helpers/contextualHelpers.js:50]: @tbsbdr suggested so IIRC, but I'm happy with either (or another suggestion)!

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 1 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue]: Taken care of, thx

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 2 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue]: Taken care of, thx

File: packages/web-app-files/src/helpers/contextualHelpers.js (hunk 3 above)
Comment (tbsbdr) [reply packages/web-app-files/src/helpers/contextualHelpers.js:50]: @kulmann yes, I guess "parent folder" is quite technical, thats why I suggested the "folders it is in" text.

Comment (tbsbdr) [reply packages/web-app-files/src/helpers/contextualHelpers.js:50]: @mmattel do you have an opinion if we should write "parent" or "folders it is in"?
screenie_Brave Browser_2022-06-20_at_14-14-21@2x

**Review by tbsbdr — CHANGES_REQUESTED** [review]
All indirect links should be collapsed initially otherwise the right sidebar welcomes the user quite crowded (presumably).

**Comment by pascalwengerter** [comment]
> All indirect links should be collapsed initially otherwise the right sidebar welcomes the user quite crowded (presumably).

They are initially collapsed (not in the dockerized environment since that mirrors the CI behavior). PR needs a rebase though

**Comment by pascalwengerter** [comment]
> lgtm

You'll need to add an "approving" review, a simple `lgtm` comment doesn't overwrite the changes you requested before 😉

**Review by kulmann — APPROVED** [review]
👍

**Review by tbsbdr — APPROVED** [review]
