### PR TITLE
[full-ci] enable capability loading for password protected public links

### LINKED ISSUE #5863: No capabilities in public context with password
### Steps to reproduce
1. Receive a public link share with password
2. Don't see any behavior that is communicated via capabilities from the backend

### Expected behaviour
Not necessarily all capabilities, but at least the most interesting ones should be available for the `web` frontend in an unauthenticated password protected context

### Actual behaviour
No capabilities are available in an unauthenticated password protected context since they only get loaded when initializing a user session (https://github.com/owncloud/web/blob/808be1ac3bed026d7ca1d2f0820f989d97665e4a/packages/web-runtime/src/store/user.js#L99)

### Qualification
- [x] Check if fetching capabilities is authenticated in OC10
- [x] Check if fetching capabilities is authenticated in oCIS

### PR DESCRIPTION
**Pull request by fschade**
## Description
as title says, enable capability loading for password protected public links.

## Related Issue
- Fixes #5863
- Needs: https://github.com/owncloud/ocis/pull/3229

## Motivation and Context
https://github.com/owncloud/web/issues/5863

## How Has This Been Tested?
- unit & integration tests

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [X] Code changes

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/23008/55/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:50

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/23008/67/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicBasic-publicLinkPublicActions_feature-L18.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/23018/67/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicBasic-publicLinkPublicActions_feature-L18.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by fschade** [comment]
@diocas can you please test the pr if it fit your needs? To test it please use this ocis branch https://github.com/owncloud/ocis/pull/3229

File: packages/web-app-files/src/views/PublicFiles.vue [hunk 1]
```diff
@@ -108,10 +104,10 @@ const unauthenticatedUserReady = async (router, store) => {
   // ocis at the moment is not able to create archives for public links that are password protected
   // till this is supported by the backend remove it hard as a workaround
```
Comment (kulmann) [inline packages/web-app-files/src/views/PublicFiles.vue:105]: I guess the fact that the archiver doesn't support password protected public link is not solved, so this still needs to be done. But is it tracked in a reva ticket? Would be helpful to have the issue link here, so that it's easier to validate if the check can be removed.

**Comment by fschade** [comment]
@kulmann i need to (re)-test it with current ocis master, ill do that today after having bumped the web-rc.1 in ocis.

File: packages/web-app-files/src/views/PublicFiles.vue (hunk 1 above)
Comment (fschade) [reply packages/web-app-files/src/views/PublicFiles.vue:105]: https://github.com/owncloud/web/issues/6515

Comment (kulmann) [reply packages/web-app-files/src/views/PublicFiles.vue:105]: Thank you! Can you please add the issue link to the comment in the code?

Comment (kulmann) [reply packages/web-app-files/src/views/PublicFiles.vue:105]: Oh, you did. sorry...

**Review by kulmann — APPROVED** [review]
Nice 😍

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/23222/68/1
The following scenarios passed on retry:
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:169

**Comment by ownclouders** [comment]
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/23222/69/1
The following scenarios passed on retry:
- webUITrashbinDelete/trashbinDelete.feature:105
