### PR TITLE
Fix bugs in resolving icon and color for file extension

### LINKED ISSUE #10031: Not all the archive files have appropriate icons
## Describe the bug
The files tar.gz and tar.bz2 don't have the appropriate icon in a UI

## Steps to reproduce
1. Create the archive files `tar cfvj archive.tar.bz2 file.txt`, `tar cfzv archive.tar.gz file.txt`
2. Upload the files to the personal space

## Expected behavior
The archive files have appropriate icons

## Actual behavior
The archive files have the default icons

## Setup
Please describe how you started the server and provide a list of relevant environment variables or configuration files.

<details>

<p>

```console
OCIS_XXX=somevalue
OCIS_YYY=somevalue
PROXY_XXX=somevalue
```

</p>
</details>

## Additional context
Screenshot 2023-11-21-1

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes #10031
- Makes #9966 work properly

### CODE REVIEW

File: packages/design-system/src/components/OcResourceIcon/OcResourceIcon.vue [hunk 1]
```diff
@@ -92,12 +87,9 @@ export default defineComponent({
         return defaultFolderIcon
       }
 
-      let icon =
-        (iconMapping[unref(extension)] as IconType) ||
-        iconMappingInjection?.mimeType[unref(mimeType)] ||
-        iconMappingInjection?.extension[unref(extension)]
+      let icon = resolveFileIcon(unref(extension))
```
Comment (kulmann) [inline packages/design-system/src/components/OcResourceIcon/OcResourceIcon.vue:90]: a) can be a const
b) you dropped all the injection now, right?! that's the mechanism that let's viewer/editor apps register icons for file types (e.g. the gpx-viewer app).

**Review by kulmann — CHANGES_REQUESTED** [review]

File: packages/design-system/src/components/OcResourceIcon/OcResourceIcon.vue (hunk 1 above)
Comment (pascalwengerter) [reply packages/design-system/src/components/OcResourceIcon/OcResourceIcon.vue:90]: a) true, thx!
b) there's still some mapping in `announceApplicationsReady` which I figured would be sufficient for viewer/editor apps at first glance, but I haven't really investigated tbh

**Review by kulmann — APPROVED** [review]
💪
