### PR TITLE
Context route auth redirect

### LINKED ISSUE #6045: Open a document in a external app via bookmark fails
### Steps to reproduce
1. Open a office document with OnlyOffice / Collabora / CodiMD
2. Copy the URL
3. Open the URL in a private / incognito tab

### Expected behaviour
- the user is redirected to the login form
- after successful authentication, the document opens with the respective app

### Actual behaviour
- the user sees a white screen and a basic auth dialog

### Environment ownCloud Infinite Scale
**Version:** 1.15.0-rc1 with Web 4.5.0

**Updated from an older Infinite Scale or fresh install:** Fresh install

**Where did you install Infinite Scale from:** Docker

### LINKED ISSUE #6069: New requests to external apps are unauthenticated
If I try to open a file in an external app by directly copy-pasting a URL in the browser (authentication is provided by keycloak), there's no redirection to keycloak so the corresponding requests are unauthenticated.

For example, if I paste this endpoint in the browser `#/external/ZW9zaG9tZS1nOjk0NTQ1MTM2/CodiMD`, no redirection to keycloak happens and the request to the `capabilities` endpoint fails with 401.

### PR DESCRIPTION
**Pull request by kulmann**
## Description
This PR includes the contextRoute of the next route when checking if authentication is required.

In the (hopefully very near) future this can be expanded to public links with password protection. But for now this simple PR solves the case of bookmarks to editors having a file open from a private context.

## Related Issue
- Fixes #6045
- Fixes #6069

## How Has This Been Tested?
- manually... I don't see much room for tests in the current state of the implementation.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

File: packages/web-app-external/src/components/LoadingScreen.vue [hunk 1]
```diff
@@ -4,3 +4,9 @@
     <p v-translate class="oc-invisible">Loading app</p>
   </div>
 </template>
+
+<script>
+export default {
```
Comment (kulmann) [inline packages/web-app-external/src/components/LoadingScreen.vue:9]: Just added the script part to give the component a name and let my IDE give the imports pretty colors.

File: packages/web-runtime/src/router/index.js [hunk 2]
```diff
@@ -1,6 +1,7 @@
 import get from 'lodash-es/get.js'
 import Vue from 'vue'
-import Router from 'vue-router'
+// eslint-disable-next-line no-unused-vars
+import Router, { Route } from 'vue-router'
```
Comment (kulmann) [inline packages/web-runtime/src/router/index.js:4]: `Route` is not used in code but in a docblock. Apparently eslint doesn't consider docblocks.

File: packages/web-app-external/src/index.js [hunk 3]
```diff
@@ -15,13 +15,13 @@ const appInfo = {
 const routes = [
   {
     name: 'apps',
-    path: '/:file_id/:app?',
+    path: '/:contextRouteName/:file_id/:app?',
```
Comment (kulmann) [inline packages/web-app-external/src/index.js:18]: Added the contextRouteName so that we can check the auth requirements of the context route (and redirect to IDP login page if coming from a private context).

**Review by diocas — APPROVED** [review]

**Review by fschade — APPROVED** [review]
👍

File: packages/web-app-files/src/mixins/fileActions.js [hunk 4]
```diff
@@ -241,6 +241,7 @@ export default {
       const routeData = this.$router.resolve({
         name: 'external-apps',
         params: {
+          contextRouteName: this.$route.name,
```
Comment (dschmidt) [inline packages/web-app-files/src/mixins/fileActions.js:244]: I know I'm late but this would have been a chance to introduce a common helper for params to external and the other apps.

Comment (kulmann) [reply packages/web-app-files/src/mixins/fileActions.js:244]: Would you like to do that in a separate PR? 😇 and/or create an issue? 😊
