### PR TITLE
[full-ci] Small fixes

### LINKED ISSUE #5618: [Bug] Public link site: remove "New" btn
## Problem

- **New button** If I receive a public link with read-only permissions, the new-Button is still shown on the public link site.
~~- **Context menu** no context menu is shown on righclick or 3-dots menu~~

### Steps to reproduce
1. login to https://ocis.ocis-web.latest.owncloud.works
2. upload a file
3. create a public link for this file with role **"viewer"**
4. open this link in a private window
5. "new" button is displayed, ~~no context menu showing~~

### Expected behaviour
- hide the New button, if you dont have write-permission
- no jumpy layout when selecting / deselecting files (batch actions become visible)
- ~~provide context menu via 3-dots menu~~
- ~~provide context menu via rightclick menu~~

### Actual behaviour
~~- click on 3-dots menu: noting happens~~
- righclick on file: shows browser-context menu

### LINKED ISSUE #6022: Accessible breadcrumb current folder info broken
### Steps to reproduce
1. login
2. create some folders and resources
3. inspect `<p class="... oc-breadcrumb-sr"> ...`

### Expected behaviour
if folder is empty and you add some content it should update (reactivity), then it should render the info with the `itemCount` instead of the raw output.

### Actual behaviour
no reactivity and no placeholder replacement

### Screenshot
Bildschirmfoto 2021-11-14 um 15 25 44

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Description
Code cleanup, changelog addition and a fixes issue

## Related Issue
- Fixes #5618
- Fixes https://github.com/owncloud/web/issues/5591
- Fixes #6022

### CODE REVIEW

**Review by dschmidt — APPROVED** [review]

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingInternal3</strong> https://drone.owncloud.com/owncloud/web/24264/61/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUIOperationsWithFolderShares-accessToSharesFolder_feature-L34.png
  

### webUIOperationsWithFolderShares-accessToSharesFolder_feature-L43.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

**Comment by pascalwengerter** [comment]
> Results for **oCISSharingInternal3** https://drone.owncloud.com/owncloud/web/24264/61/1
> 💥 The acceptance tests failed on retry. Please find the screenshots inside ...
> 💥 The acceptance tests pipeline failed. The build has been cancelled.

Needs changes to the ways to the way acceptance tests check that `it should not be possible to create files using the webUI` 🙄 taking care later, switching this PR to [full-ci] in the meantime

File: changelog/unreleased/enhancement-permission-based-upload-create-buttons [hunk 1]
```diff
@@ -0,0 +1,6 @@
+Enhancement: Permission-based upload and create buttons
+
+Instead of showing disabled "Upload" and "New" buttons, we now hide them for the user if they lack permissions for the currently viewed folder.
```
Comment (kulmann) [inline changelog/unreleased/enhancement-permission-based-upload-create-buttons:3]: The described behaviour is only the desired behaviour for public links. For shares in an authenticated context we ( @tbsbdr and myself ) figured that disabling if the user lacks create permissions is better to avoid a jumpy layout when going back and forth.

**Review by kulmann — CHANGES_REQUESTED** [review]

File: packages/web-app-files/src/components/AppBar/CreateAndUpload.vue [hunk 2]
```diff
@@ -195,6 +194,10 @@ export default {
       }
     },
 
+    showActions() {
+      return !(this.uploadOrFileCreationBlocked && this.publicPage())
```
Comment (kulmann) [inline packages/web-app-files/src/components/AppBar/CreateAndUpload.vue:198]: for the record: I'd like to get rid of the `publicPage` checks.

**Review by kulmann — APPROVED** [review]

File: packages/web-app-files/src/components/AppBar/CreateAndUpload.vue (hunk 2 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/AppBar/CreateAndUpload.vue]: Removed it in CreateAndUpload.vue and two more Vue files, it's now only being used in two action mixings and the upload mixin we might be able to delete when introducing Uppy

Comment (pascalwengerter) [reply packages/web-app-files/src/components/AppBar/CreateAndUpload.vue]: *replaced it in favor of a `useActiveLocation(isLocationPublicActive, ...)` check
