### PR TITLE
Purge config option options.sidebar.shares.showAllOnLoad

### LINKED ISSUE #11212: Get rid of the options.sidebar.shares.showAllOnLoad config option
## Describe the bug
Config optioon `options.sidebar.shares.showAllOnLoad` only exists to make life easier in CI/e2e tests. The real world behaviour is and should be, that only the first 3 shares are shown and then a `Show all` button is being rendered if there are more shares.

Adapt the e2e tests to make the click on `Show all` if needed, then delete the config option.

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #11212 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 1]
```diff
@@ -68,10 +68,8 @@
         class="indirect-link-list-toggle"
         appearance="raw"
         @click="toggleLinkListCollapsed"
-      >
-        <span v-text="collapseButtonTitle" />
-        <oc-icon :name="collapseButtonIcon" fill-type="line" />
-      </oc-button>
+        v-text="collapseButtonTitle"
```
Comment (JammingBen) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:71]: Please leave this as it was, it's considered bad practice to use `v-text` on components since it can break the component's content. Your IDE linter should also complain 🤔

Comment (AlexAndBear) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:71]: does not

Comment (JammingBen) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:71]: Then something is misconfigured. `eslint` rightfully gives a warning.

**Review by JammingBen — APPROVED** [review]
👍
