### PR TITLE
[full-ci] Redesign "Create and manage sharing links"

### LINKED ISSUE #6323: Checking for password enforcement on public links is utterly broken
`this.capabilities.files_sharing.public.password.enforced_for` returns an object with three boolean values, while we're comparing them via `=== 1` to evaluate if they're relevant

https://github.com/owncloud/web/blob/b40021703e37143810058f9f06cdfba1f76c7863/packages/web-app-files/src/components/SideBar/Links/PublicLinks/LinkEdit.vue#L267

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes https://jira.owncloud.com/browse/WEB-839
- Fixes #6323

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/24732/70/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicBasic-publicLinkCreate_feature-L11.png
  

### webUISharingPublicBasic-publicLinkCreate_feature-L28.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L33.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L34.png
  

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles_feature-L35.png
  


</p></details>

File: changelog/unreleased/enhancement-update-ods [hunk 1]
```diff
@@ -0,0 +1,15 @@
+Enhancement: Update ODS to v13.1.0-rc.4
```
Comment (pascalwengerter) [inline changelog/unreleased/enhancement-update-ods:1]: Needs update to current RC

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 2]
```diff
@@ -261,14 +345,133 @@ export default defineComponent({
...
+        id: link.id,
+        client: this.$client,
+        params
+      })
+        .then(onSuccess)
+        .catch((e) => {
+          onError(e)
+          console.error(e)
+          this.showMessage({
+            title: this.$gettext('Error when updating public link'),
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:428]: I think the wording in other error messages is something like `Failed to update link`.

Comment (kulmann) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:428]: And I think you can already ditch the `public` in texts about links.

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 3]
```diff
@@ -261,14 +345,133 @@ export default defineComponent({
...
+      await this.removeLink({ client, share, resource, storageId: this.currentStorageId })
+        .then(
+          this.showMessage({
+            title: this.$gettext('Public link was deleted successfully')
+          })
+        )
+        .catch((e) => {
+          console.error(e)
+          this.showMessage({
+            title: this.$gettext('Error deleting public link'),
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:471]: same here again about consistency of error message wordings

**Review by kulmann — CHANGES_REQUESTED** [review]
added some comments. feels good so far!
additional issues:
- selected date in date picker of public link doesn't get applied anymore (blocking for merge)
- options dropdown for a link list item feels a bit too compact, but can be solved later on

File: packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+  components: { CopyToClipboardButton },
+  props: {
+    link: {
+      type: Object,
+      required: true
+    }
+  },
+  computed: {
+    linkName() {
+      return this.link.name ? this.link.name : this.link.token
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue:37]:
```suggestion
      return this.link.name || this.link.token
```

File: packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue [hunk 5]
```diff
@@ -0,0 +1,60 @@
+<template>
+  <div class="oc-mb-s oc-width-1-1">
+    <h5 class="oc-text-truncate oc-files-file-link-name oc-my-s" v-text="linkName" />
+    <div
+      class="oc-flex oc-flex-middle oc-flex-between oc-width-1-1 oc-p-s"
+      style="background-color: var(--oc-color-input-bg); border: 1px solid white"
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue:6]: worth to add a css class?

File: packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue [hunk 6]
```diff
@@ -0,0 +1,60 @@
+<template>
+  <div class="oc-mb-s oc-width-1-1">
+    <h5 class="oc-text-truncate oc-files-file-link-name oc-my-s" v-text="linkName" />
```
Comment (kulmann) [inline packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue:3]: shouldn't this be an `h4`?

**Review by kulmann — CHANGES_REQUESTED** [review]

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 7]
```diff
@@ -110,8 +120,89 @@ export default defineComponent({
...
     ...mapGetters(['capabilities', 'configuration']),
-    ...mapState('Files', ['sharesTree']),
     ...mapState(['user']),
+    ...mapState('Files', ['sharesTree']),
+
+    addButtonLabel() {
+      return this.$gettext('Add link')
+    },
+    addButtonAriaLabel() {
+      return this.$gettext('Create new public link')
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:130]: Good point, removing it

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 8]
```diff
@@ -110,8 +120,89 @@ export default defineComponent({
...
+      if (this.capabilities?.files_sharing?.public?.defaultPublicLinkShareName) {
+        return this.capabilities?.files_sharing?.public?.defaultPublicLinkShareName
+      }
+      return ''
+    },
+
+    globalExpirationDate() {
+      const expireDate = this.capabilities.files_sharing.public.expire_date
+
+      console.log('expireDate', expireDate)
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:143]: Can go

File: packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue (hunk 5 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/PublicLinks/NameAndCopy.vue:6]: True, yeah. Hacking leftover

File: packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue [hunk 9]
```diff
@@ -0,0 +1,480 @@
...
+      if (password === '') {
+        return this.setModalInputErrorMessage(this.$gettext("Password can't be empty"))
+      }
+      return this.setModalInputErrorMessage(null)
+    },
+
+    showPasswordModal() {
+      const modal = {
+        variation: 'passive',
+        title: this.link.password ? this.$gettext('Edit password') : this.$gettext('Add password'),
```
Comment (fschade) [inline packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue:422]: `this.$gettext(this.link.password ? 'Edit password' : 'Add password')`

File: packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+        },
+        true
+      )
+    }
+  }
+}
+</script>
+
+<style scoped>
+.link-name-container {
```
Comment (fschade) [inline packages/web-app-files/src/components/SideBar/Shares/Links/NameAndCopy.vue:60]: intentional use of `scoped`?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 11]
```diff
@@ -7,85 +7,94 @@
...
-            >
-            <oc-contextual-helper v-if="helpersEnabled" v-bind="viaLinkHelp" />
-          </p>
+        <h3 class="oc-text-bold oc-m-rm oc-text-initial">
+          <span v-text="linksHeading" />
+          <oc-contextual-helper v-if="helpersEnabled" v-bind="viaLinkHelp" />
+        </h3>
+        <div v-if="canCreatePublicLinks" class="oc-mt-m">
+          <!-- quicklink goes here -->
+          <!-- <hr class="oc-my-s"> -->
```
Comment (fschade) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:16]: leftover?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 12]
```diff
@@ -110,8 +119,75 @@ export default defineComponent({
...
+        return {
+          role,
+          name: role.name,
+          label: this.$gettext(role.label)
+        }
+      })
+
+      // add empty permission link if oCIS for alias link
+      return [
+        // { role: null, name: 'Alias link', label: this.$gettext('Only invited people') },
```
Comment (fschade) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:177]: leftover?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 13]
```diff
@@ -261,14 +324,133 @@ export default defineComponent({
...
+            resource: this.highlightedFile
+          })
+      }
+      this.createModal(modal)
+    },
+
+    async deleteLink({ client, share, resource }) {
+      this.hideModal()
+      // removeLink currently fetches all shares from the backend in order to reload the shares indicators
+      // TODO: Check if to-removed link is last link share and only reload if it's the last link
```
Comment (fschade) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:440]: leftOver?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue [hunk 14]
```diff
@@ -261,14 +324,133 @@ export default defineComponent({
...
+      await this.removeLink({ client, share, resource, storageId: this.currentStorageId })
+        .then(
```
Comment (fschade) [inline packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:442]: please avoid mixing of then and await.

File: packages/web-app-files/src/helpers/resources.ts [hunk 15]
```diff
@@ -442,7 +442,7 @@ function _buildLink(link): Share {
     permissions: link.permissions,
     description,
     stime: link.stime,
-    name: typeof link.name === 'string' ? link.name : '',
+    name: typeof link.name === 'string' ? link.name : (link.token as string),
```
Comment (fschade) [inline packages/web-app-files/src/helpers/resources.ts:445]: what's the reason to use link.token as a fallback instead of the empty string like before?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 11 above)
Comment (kulmann) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:16]: no, reminder for future implementation (quicklink)

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 12 above)
Comment (kulmann) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:177]: no, reminder for future implementation (alias link / permissions=0), but I'd a prefer an actual ShareRole instance here instead of JSON.

File: .drone.star [hunk 16]
```diff
@@ -795,10 +795,10 @@ def beforePipelines(ctx):
            pipelinesDependsOn(yarnlint(ctx), yarnCache(ctx))
 
 def stagePipelines(ctx):
-    unit_test_pipelines = unitTests(ctx)
-    e2e_pipelines = e2eTests(ctx)
+    # unit_test_pipelines = unitTests(ctx)
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply .drone.star]: Resolved

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 14 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:442]: Wasn't it us two that came up with this? Glad to replace it with something else, any suggestions?

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 13 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:440]: Todo for the future as "out of scope" for this PR

File: packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue (hunk 9 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue:422]: Don't think that's a viable way to trigger transifex though 🤔

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 12 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:177]: To be cleaned up in the near future in another PR

File: packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue (hunk 11 above)
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue:16]: To be cleaned up in the near future in another PR

File: packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue [hunk 17]
```diff
@@ -0,0 +1,247 @@
...
+          <template #default="{ togglePopover }">
+            <oc-button
+              id="files-links-expiration-btn"
+              data-testid="recipient-datepicker-btn"
+              class="oc-width-1-1 expiration-dialog-btn"
+              justify-content="space-between"
+              gap-size="xsmall"
+              @click="togglePopover"
+            >
+              <translate v-if="!link.expiration" key="no-expiration-date-label"
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue:50]: ESlint doing its thing 🤷🏽

File: packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue [hunk 18]
```diff
@@ -0,0 +1,247 @@
...
+          v-text="$gettext('Remove password')"
+        />
+      </div>
+      <hr class="divider" />
+      <div class="oc-mb">
+        <oc-button id="oc-files-file-link-cancel" :disabled="saving" @click="closeForm">
+          <translate>Cancel</translate>
+        </oc-button>
+        <oc-button
+          v-if="saving"
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue:96]: Agreed, thx

File: packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue [hunk 19]
```diff
@@ -0,0 +1,480 @@
...
+        })
+        if (!this.expirationDate.enforced) {
+          result.push({
+            id: 'remove-expiration',
+            title: this.$gettext('Remove expiration date'),
+            method: () =>
+              this.updateLink({
+                link: {
+                  ...this.link,
+                  expiration: ''
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue:233]: Needs to be an empty string so the backend actually deletes the expiry date ;)

File: packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue [hunk 20]
```diff
@@ -0,0 +1,480 @@
...
+      <oc-drop
+        ref="editPublicLinkRoleDropdown"
+        :drop-id="`edit-public-link-role-dropdown`"
+        :toggle="`#edit-public-link-role-dropdown-toggl-${link.id}`"
+        padding-size="remove"
+        mode="click"
+      >
+        <oc-list class="roleDropdownList">
+          <li v-for="(descriptor, i) in availableRoleOptions" :key="`role-dropdown-${i}`">
+            <oc-button
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue:23]: Agreed & changed, thx

[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue:23]: Going for `roleOption.label.toLowerCase()` inside the string interpolation, should be unique enough

File: packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue [hunk 21]
```diff
@@ -0,0 +1,247 @@
...
+    })
+  },
+  methods: {
+    createLink() {
+      this.saving = true
+      this.$emit('createPublicLink', {
+        link: {
+          ...this.link,
+          permissions: this.link.role.role.bitmask(false).toString()
+        },
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue:235]: I haven't fully understood why we do

```
map((role) => {
        return {
          role,
          name: role.name,
          label: this.$gettext(role.label)
        }
      }
```

in the wrapping FileLinks.vue component, essentially creating a new role object containing the full role and extracting/copying two attributes up a level?

File: packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue [hunk 22]
```diff
@@ -0,0 +1,247 @@
...
+      }
+
+      return this.$gettext('Password')
+    },
+    roleLabel() {
+      return this.$gettext('Role')
+    },
+
+    passwordEnforcedForRole() {
+      const currentRole = this.availableRoleOptions.find((role) => {
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue:189]: Done

File: packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue [hunk 23]
```diff
@@ -0,0 +1,247 @@
...
+      }
+      if (this.passwordEnforced.read_write === true) {
+        return canRead && canCreate
+      }
+      return false
+    },
+
+    isValid() {
+      const passwordValid = !(this.passwordEnforcedForRole && !this.link.password)
+      // needs to check expiration date min/max!
```
[the remark this answers is not in the document]
Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Shares/Links/CreateForm.vue:210]: Just checked and it doesn't, actually 😅 now the DatePicker gets initialized properly so the expiration date can't be set outside of min and max!

**Review by fschade — APPROVED** [review]
LGTM 🚀

**Review by kulmann — CHANGES_REQUESTED** [review]
One last remaining thing: public links can't be modified anymore because there is a malformed `DateTime` creation. Otherwise LGTM, will approve after that's fixed.

**Review by kulmann — APPROVED** [review]
Meh. Couldn't reproduce the `DateTime` conversion issue anymore. Super happy to have this merged! Feels so well aligned with regular shares now, regarding their look and feel 🤩
