### PR TITLE
fix(view rendering): cancel overlapping resource requests

### LINKED ISSUE #5085: Responses are rendered in different places
If I send a request to list a large directory /`A/B/C`.
In the mean time I change path to `/Z`.
Request to `/A/B/C` finished and shows the content of `C` inside `Z`.

The expected behaviour is that the response should not be rendered as this is not the original path it was requested.

### PR DESCRIPTION
**Pull request by fschade**
## Description
While testing the files app with heavy load we've found some cases where it could happen that the ui breaks or displays wrong list of files, this only happened when navigation fast between the different views.

To dig a bit deeper we've used the mounted and created hooks to load current views resources for files app, which can lead to overlapping rendering when view `A` still prepares the resource data and the user quickly switches to view `B`. If then `B` is rendered before `A` is finished vue renders the view `A` into `B`.

This is an overall problem and is present in many projects, where state, data and timing overlaps. This potentially is a memory leak also, in cases where `this` is used and the instance isn't around anymore.

This PR fixes those cases for the files app by superseding the usual vue behavior and use iterable generators from vue-concurrency  and cancel the preparation step (request loading, state loading, view rendering) when not needed anymore.

## Related Issue

- Fixes #5085
- Related #5875 

## Motivation and Context
get a fast and concurrency safe ui

## How Has This Been Tested?

- test suite
- hammering the ui locally

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Technical debt
- [ ] Tests

## Checklist:

- [X] Code changes
- [X] Unit tests added

## Open tasks:

- [ ] none expect decision and testing ;)

### CODE REVIEW

File: changelog/unreleased/bugfix-overlapping-view-requests [hunk 1]
```diff
@@ -0,0 +1,10 @@
+Bugfix: Fix overlapping requests in files app
+
+In some cases the files app tended to display the wrong resources when navigation quickly through the views. This happened because the resource provisioning step wasn't canceld.
```
Comment (kulmann) [inline changelog/unreleased/bugfix-overlapping-view-requests:3]:
```suggestion
In some cases the files app tended to display the wrong resources when navigating quickly through the views. This happened because the resource provisioning step wasn't canceled.
```

File: changelog/unreleased/bugfix-overlapping-view-requests [hunk 2]
```diff
@@ -0,0 +1,10 @@
...
+This is now fixed by using vue-concurrency which on a high level wraps iterable generators which are cancelable.
```
Comment (kulmann) [inline changelog/unreleased/bugfix-overlapping-view-requests:4]:
```suggestion
This is now fixed by using vue-concurrency which on a high level wraps iterable generators which are cancelable. We're using it to wrap the resource loading and cancel it as soon as the resource set is not needed anymore.
```

File: packages/web-app-files/src/views/Favorites.vue [hunk 3]
```diff
@@ -76,9 +77,19 @@ export default {
     MixinFilesListFilter
   ],
 
-  data: () => ({
-    loading: true
-  }),
+  setup() {
+    const loadResourcesTask = useTask(function* (signal, ref, sameRoute, path = null) {
+      yield new Promise((resolve) => setTimeout(resolve, 2000))
```
Comment (kulmann) [inline packages/web-app-files/src/views/Favorites.vue:82]: dev leftover

File: packages/web-app-files/src/views/Favorites.vue [hunk 4]
```diff
@@ -76,9 +77,19 @@ export default {
     MixinFilesListFilter
   ],
 
-  data: () => ({
-    loading: true
-  }),
+  setup() {
+    const loadResourcesTask = useTask(function* (signal, ref, sameRoute, path = null) {
```
Comment (kulmann) [inline packages/web-app-files/src/views/Favorites.vue:81]: Params `sameRoute` and `path` are not needed here

**Review by kulmann — COMMENTED** [review]
😍😍😍

**Comment by kulmann** [comment]
Linter is not happy. ;-) Tested it locally and wasn't able to break it. 🚀

**Review by kulmann — APPROVED** [review]
❤️
