### PR TITLE
Fix #6917 - sharing indicators&description for spaces

### LINKED ISSUE #6917: Link sharing indicator for spaces is not working
### Steps to reproduce
1. Create a public link for a space
2. Open the sidebar for this space
3. Click on the sharing indicator where it says "1 link giving access" -> nothing happens

image

### PR DESCRIPTION
**Pull request by pascalwengerter**
## Related Issue
- Fixes #6917

### CODE REVIEW

File: packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue [hunk 1]
```diff
@@ -138,10 +115,64 @@ export default defineComponent({
...
+        )
+      }
+    },
+    openSharesPanelHint() {
+      return this.$gettext('Open share panel')
+    },
+    openSharesPanelLinkHint() {
+      return this.$gettext('Open member list in share panel')
+    },
+    openSharesPanelMembersHint() {
```
Comment (JammingBen) [inline packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue:173]:
```suggestion
    openSharesPanelLinkHint() {
```

**Comment by ownclouders** [comment]
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/25438/56/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUICreateFilesFolders-createFile_feature-L31.png
  


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

File: packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue [hunk 2]
```diff
@@ -138,10 +115,64 @@ export default defineComponent({
...
+      } else {
+        return this.$gettextInterpolate(
+          'This space has %{memberShareCount} members and %{linkShareCount} links.',
+          {
+            memberShareCount: this.memberShareCount,
+            linkShareCount: this.linkShareCount
+          }
+        )
+      }
+    },
```
Comment (JammingBen) [inline packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue:166]: I still think this can be simplified to something like:

```
if (this.linkShareCount === 1) {
   return this.$gettextInterpolate('This space has %{memberShareCount} members and %{linkShareCount} link.', ....)
} else {
   return this.$gettextInterpolate('This space has %{memberShareCount} members and %{linkShareCount} links.', ....) 
}
```

Comment (pascalwengerter) [reply packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue]: I hope I could simplify the changes a bit 😰 discussed the approach with @kulmann and we decided to start counting space members _including_ the owner/manager (previously `hasMembers` started as `> 1`), which made some logic redundant.

File: packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue [hunk 3]
```diff
@@ -12,91 +12,68 @@
...
-          </td>
-        </tr>
-        <tr>
-          <th scope="col" class="oc-pr-s" v-text="$gettext('Quota')" />
-          <td>
-            <space-quota :space-quota="space.spaceQuota" />
-          </td>
-        </tr>
-      </table>
+    <div v-if="hasShares" class="oc-flex oc-flex-middle oc-mb-m oc-text-small" style="gap: 15px">
```
Comment (lookacat) [inline packages/web-app-files/src/components/SideBar/Details/SpaceDetails.vue:15]: minor finding, inline style :)

**Review by JammingBen — APPROVED** [review]
