### PR TITLE
[full-ci] Fix #4893: Make sure filenames (and extensions) are properly updated in file list and sidebar after rename

### LINKED ISSUE #4893: Unexpected behavior when renaming files
### Steps to reproduce
In the sidebar,
1. Rename a `folder`: The name updates correctly in both file table and sidebar heading without a page reload
2. Rename a `file` without touching the filetype-extension (e.g. change `demo.txt` to `demo2.txt`: The name updates correctly in both file table and sidebar heading without a page reload
3. Rename a `file` including the filetype-extension (e.g. change `demo.txt` to `demo.md`: The name updates correctly in the sidebar heading, but in the File table only the file name (and not the filetype-extension) gets updated dynamically. Updating the filetype-extension requires a full page reload

### Expected behaviour
File name should correctly update in Files table without having to perform a page reload

### Actual behaviour
File name only updates in Files table when name (and not extension) are changed

### Server configuration
**Backend:** oCIS (unclear about OC10)

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
Make sure filenames (and extensions) are properly updated in file list and sidebar after rename.

## Related Issue

- Fixes #4893 

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

### CODE REVIEW

**Comment by dschmidt** [comment]
I haven't added a test for the files list view, but there is one in this PR: https://github.com/owncloud/web/pull/6110/files

How do we go on with this? Should we merge them together before we merge to master? Or should we merge them sequentially?

**Review by fschade — APPROVED** [review]
looks good to me, 1 tiny fininding which is optional, thanks for taking care

File: packages/web-app-files/src/components/SideBar/SideBar.vue [hunk 1]
```diff
@@ -214,9 +209,9 @@ export default {
         return
       }
 
-      if (newFile.id !== oldFile?.id) {
-        this.fetchFileInfo()
-      }
+      // always update even if the id is unchanged
```
Comment (fschade) [inline packages/web-app-files/src/components/SideBar/SideBar.vue:212]: not sure if the comment is needed, maybe if someone reads it in the future it could be hard to understand without the context from the past.

Comment (dschmidt) [reply packages/web-app-files/src/components/SideBar/SideBar.vue:212]: Yeah, true, but noone should pass this and think "Oh I can optimize this" ...  on the other hand we have a regression test for that now, so we can probably indeed remove it.

Comment (dschmidt) [reply packages/web-app-files/src/components/SideBar/SideBar.vue]: Removed

**Comment by fschade** [comment]
> I haven't added a test for the files list view, but there is one in this PR: https://github.com/owncloud/web/pull/6110/files
> 
> How do we go on with this? Should we merge them together before we merge to master? Or should we merge them sequentially?

It’s ok to not have a acceptance test in place, it’s verified in unit tests.

maybe @ScharfViktor wanna have in smoke tests do demonstrate basic file operations.

**Comment by pascalwengerter** [comment]
Restarted flaky smoke tests in CI, PR looks great to me!

**Review by kulmann — APPROVED** [review]
Awesome 👍

**Comment by ScharfViktor** [comment]
There is a failing in the same place. I will try running it locally, maybe there is a problem

**Comment by ScharfViktor** [comment]
again in the same place. running the tests locally was successful

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/20906/44/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:111

**Comment by pascalwengerter** [comment]
Last CI run had two failures (one flaky federation sharing test in OC10, one copying an empty file on oCIS). Rebased on master to resolve conflict, bumped oCIS commit ID once more and fixed the oCIS acceptance test. Should be fine now once we pass the flaky smoke tests

**Comment by ownclouders** [comment]
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/20942/16/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingPublic</strong> https://drone.owncloud.com/owncloud/web/20942/65/1
The following scenarios passed on retry:
- webUISharingPublicManagement/publicLinkIndicator.feature:110

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/20942/54/1
The following scenarios passed on retry:
- webUISharingAcceptShares/acceptShares.feature:111

**Comment by pascalwengerter** [comment]
Finally 🙏🏽

**Comment by dschmidt** [comment]
🎉
