### PR TITLE
Dont load config routing from config.json, instead set based on cernFeatures option

### LINKED ISSUE #11216: Remove config option `option.routing`
## Describe the bug
Nobody wants to set `options.routing.idBased` to false, because that would only lead to shooting yourself in the foot. We can't drop the feature flag at the moment. But let's drop the config option and instead disable id based routing if `cernFeatures` is set to `true`.

Remember to also remove the config option `options.routing` in the ocis config struct.

### PR DESCRIPTION
**Pull request by AlexAndBear**
## Related Issue

- Fixes #11216 
- ## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

### CODE REVIEW

File: packages/web-pkg/src/composables/piniaStores/config/config.ts [hunk 1]
```diff
@@ -79,7 +81,10 @@ export const useConfigStore = defineStore('config', () => {
     theme.value = data.theme
 
     if (data.options) {
-      options.value = merge({ ...defaultOptions }, data.options)
+      // routing will not be loaded from config, but set based on cernFeatures option
+      options.value = merge({ ...defaultOptions }, omit(data.options, ['routing']))
```
Comment (AlexAndBear) [inline packages/web-pkg/src/composables/piniaStores/config/config.ts:85]: maybe the omit is not needed, just a security layer, so that routing will not be loaded at all via config

File: packages/web-pkg/src/composables/piniaStores/config/config.ts [hunk 2]
```diff
@@ -29,7 +30,8 @@ const defaultOptions = {
   },
   openAppsInTab: false,
   routing: {
-    idBased: true
+    idBased: true,
+    fullShareOwnerPaths: false
```
Comment (AlexAndBear) [inline packages/web-pkg/src/composables/piniaStores/config/config.ts:34]: Is the default correct, there is no documentation about it anywhere

Comment (kulmann) [reply packages/web-pkg/src/composables/piniaStores/config/config.ts:34]: It's optional and ocis doesn't set it, so it defaults to `false`. Your chosen default is correct :-)

**Review by kulmann — APPROVED** [review]
