### PR TITLE
Fix search context menu

### LINKED ISSUE #6293: Search results: right or left click have no effect
### Steps to reproduce
1. Login on web.owncloud.com
2. Search for "portugal" or "manual" in all files `search all files`
3. left or right click on file

### Expected behaviour

- left click: standard action
- right click: context menu

### Actual behaviour
nothing happens

### PR DESCRIPTION
**Pull request by dschmidt**
## Description
Enable/disable certain file actions outside of the file application.

## Related Issue

- Fixes #6293 

## Motivation and Context
Several file actions (currently) work or don't work outside the files app. In general anything that just interacts with the backend works fine, actions that rely on e.g., the sidebar, don't work in the search app for instance.

## How Has This Been Tested?

- needs oC 10

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
Decide whether we want to make the search results selectable in the ResourcesTable, to prepare for multi select and archive download.
Currently we have no search in oCIS and `isDownloadAsArchiveAvailable` is false on oC 10, so currently it's probably just confusing for no benefit... tying this to `isDownloadAsArchiveAvailable` would be possible, but feels weird as well ... happy to hear other opinions :) 

Adding a check whether

### CODE REVIEW

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/22825/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-2-16-06-08-35.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-shares-file-to-brian-alice-2022-2-16-06-09-54.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-shares-file-to-brian-brian-2022-2-16-06-09-59.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-shares-folder-with-file-to-brian-alice-2022-2-16-06-11-07.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/22825/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-2-16-06-09-35.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-shares-file-to-brian-alice-2022-2-16-06-11-01.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-shares-file-to-brian-brian-2022-2-16-06-11-06.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22825/alice-shares-folder-with-file-to-brian-alice-2022-2-16-06-12-19.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/22827/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-2-16-06-52-17.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-shares-file-to-brian-alice-2022-2-16-06-53-36.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-shares-file-to-brian-brian-2022-2-16-06-53-40.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-shares-folder-with-file-to-brian-alice-2022-2-16-06-54-49.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/22827/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-2-16-06-53-28.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-shares-file-to-brian-alice-2022-2-16-06-54-58.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-shares-file-to-brian-brian-2022-2-16-06-55-04.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22827/alice-shares-folder-with-file-to-brian-alice-2022-2-16-06-56-18.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/22830/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-2-16-07-30-59.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-shares-file-to-brian-alice-2022-2-16-07-32-20.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-shares-file-to-brian-brian-2022-2-16-07-32-25.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-shares-folder-with-file-to-brian-alice-2022-2-16-07-33-34.zip 


</p></details>

**Comment by ownclouders** [comment]
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/22830/10/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-2-16-07-31-49.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-shares-file-to-brian-alice-2022-2-16-07-33-15.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-shares-file-to-brian-brian-2022-2-16-07-33-20.zip 

#### npx playwright show-trace https://cache.owncloud.com/owncloud/web/tracing/22830/alice-shares-folder-with-file-to-brian-alice-2022-2-16-07-34-33.zip 


</p></details>

File: packages/web-app-files/src/mixins/actions/downloadArchive.js [hunk 1]
```diff
@@ -21,6 +21,7 @@ export default {
           },
           isEnabled: ({ resources }) => {
             if (
+              this.isFilesAppActive &&
```
Comment (kulmann) [inline packages/web-app-files/src/mixins/actions/downloadArchive.js:24]: Could you please add a comment here (and in the other mixins where this check is used) that we only exit for routes of the files app, because we don't want to include knowledge about other apps within the files app. Eventually we'll want to refactor the mixins into something nicer + typescript-ier and probably also want to allow registration of context actions via the extension system. But we're not there, yet.

File: packages/web-app-files/src/components/FilesList/ContextActions.vue [hunk 2]
```diff
@@ -69,6 +73,17 @@ export default {
...
   },
+  setup() {
+    const activeApp = useActiveApp()
+    const isFilesAppActive = computed(() => {
+      return activeApp === FilesApp.appInfo.id
+    })
+
+    return {
+      activeApp,
+      isFilesAppActive
```
Comment (kulmann) [inline packages/web-app-files/src/components/FilesList/ContextActions.vue:84]: This is not sufficient for the mixins, because they are also used inside batch actions. Although mixins allow this magic I'd prefer to be more explicit here and have `isFilesAppActive` defined in any mixin that uses it. I'd be fine for having another composable from this to make re-use easier and less verbose.

**Review by kulmann — CHANGES_REQUESTED** [review]

File: packages/web-app-files/src/mixins/actions/downloadArchive.js (hunk 1 above)
Comment (dschmidt) [reply packages/web-app-files/src/mixins/actions/downloadArchive.js:24]: Added comment to the `useIsFilesAppActive` composable.

File: packages/web-app-files/src/components/FilesList/ContextActions.vue (hunk 2 above)
Comment (dschmidt) [reply packages/web-app-files/src/components/FilesList/ContextActions.vue]: I tried to move this to the individual mixins, but that wasn't possible as we would be mixing options and composition api. No fun.

File: packages/web-app-files/src/components/Search/List.vue [hunk 3]
```diff
@@ -16,11 +16,14 @@
...
       :are-paths-displayed="true"
       :are-thumbnails-displayed="displayThumbnails"
-      :has-actions="false"
+      :has-actions="true"
       :is-selectable="false"
       @fileClick="$_fileActions_triggerDefaultAction"
       @rowMounted="rowMounted"
     >
+      <template #contextMenu="{ resource }">
+        <context-actions :items="[resource]" />
```
Comment (kulmann) [inline packages/web-app-files/src/components/Search/List.vue:25]: This creates the context-actions for each row in the table. Could you check if you can tmp store the right clicked resource and use a `v-if` on `context-actions` to only create the context-actions in the DOM that were right-clicked last? Otherwise you create the context-actions for each and every file row in the DOM (even if they're not shown).

**Review by kulmann — CHANGES_REQUESTED** [review]

**Review by kulmann — APPROVED** [review]
Nice improvement 🥇

**Comment by ownclouders** [comment]
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22843/66/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:94

**Comment by dschmidt** [comment]
🤩
